schema_version: 1

context:
  name: glom
  version: 25.12.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 1ae7da88be3693df40ad27bdf57a765a55c075c86c971bcddd67927403eb0069

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  python:
    entry_points:
      - glom = glom.cli:console_main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - attrs
    - boltons >=19.3.0
    - face >=20.1.1
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - glom
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - glom/test
    requirements:
      run:
        - pytest >=6.2.5
        - pyyaml ==5.4.1
        - python ${{ python_min }}.*
    script:
      - glom --help
      - pytest -vvv --capture=tee-sys -k "not test_error" glom/test

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A declarative object transformer and formatter, for conglomerating nested data.
  homepage: https://github.com/mahmoud/glom

extra:
  recipe-maintainers:
    - CJ-Wright
    - thewchan
